sudo: required
services:
  - docker

before_install:
  - docker build -t medch1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run medch1/react-test npm test -- --coverage

after_success:
  - docker build -t medch1/multi-client ./client
  - docker build -t medch1/multi-nginx ./nginx
  - docker build -t medch1/multi-server ./server
  - docker build -t medch1/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to DockerHub
  - docker push medch1/multi-client
  - docker push medch1/multi-nginx
  - docker push medch1/multi-server
  - docker push medch1/multi-worker

